const DATA = {
    "Personality traits": [
        "Self-confident",
        "Fashionable",
        "Comfortable",
        "Traditional",
        "Dogmatic",
        "Sensitive",
        "Pessimistic",
        "Inventive",
        "Strong Willed",
        "Sociable",
        "Modest",
        "Thrifty",
        "Observant",
        "Cynical",
        "Suggestible",
        "Insightful",
        "Ambitious",
        "Popular",
        "At Ease",
        "Structured",
        "Anxious",
        "Analytical",
        "Demanding",
        "Playful",
        "Peaceful",

    ],
    "Characteristics": [
        "Frugal",
        "Restless",
        "Clever",
        "Fearless",
        "Expressive",
        "Nonchalant",
        "Thorough",
        "Immature",
        "Creative",
        "Relentless",
        "Talkative",
        "Even Tempered",
        "Meticulous",
        "Fearful",
        "Experimental",
        "Decisive",
        "Formal",
        "Rigorous",
        "Self-assured",
        "Attractive",
        "Patient",
        "Cautious",
        "Historical",
        "Dispirited",
        "Reluctant",
    ],
    "Beliefs": [
        "Perceptive",
        "Bold",
        "Outgoing",
        "Unhurried",
        "Controlled",
        "Risk-averse",
        "Indulgent",
        "Confused",
        "Original",
        "Opportunistic",
        "Life of the Party",
        "Systematic",
        "Exacting",
        "Easily Excited",
        "Inquisitive",
        "Determined",
        "Entertaining",
        "Predictable",
        "Watchful",
        "Fragile",
        "Keen",
        "Venturesome",
        "Cheerful",
        "Unruffled",
        "Conforming",

    ],
    "Morals": [
        "Gullible",
        "Knowledgeable",
        "Commanding",
        "Good Mixer",
        "Accepting",
        "Crisp",
        "Sentimental",
        "Shrewd",
        "Persistent",
        "Consistent",
        "Respectful",
        "Perplexed",
        "Self - reliant",
        "Spontaneous",
        "Easy Going",
        "Conventional",
        "Fastidious",
        "Temperamental",
        "Ashamed",
        "Innovative",
        "Resourceful",
        "Appealing",
        "Tranquil",
        "Accurate",
        "Organized",
    ],
    "Motivators": [
        "Nit Picky",
        "Impulsive",
        "Astute",
        "Daring",
        "Communicative",
        "Placid",
        "Finite",
        "Emotional",
        "Agile",
        "Individualistic",
        "Conversational",
        "Laid Back",
        "Vigilant",
        "Nervous",
        "Incisive",
        "Courageous",
        "Interactive",
        "Calm",
        "Old Fashioned",
        "Preoccupied",
        "Savvy",
        "Aware",
        "Likable",
        "Restful",
        "Disciplined",
    ],
    "Conviction": [
        "Rattled",
        "Intelligent",
        "Unwavering",
        "Relaxed",
        "Pedantic",
        "Chatty",
        "Resolute",
        "Approachable",
        "Orderly",
        "Efficient",
        "Perfectionist",
        "Forgetful",
        "Single - minded",
        "Deductive",
        "Purposeful",
        "Endearing",
        "Steady",
        "Flawless",
        "Precise",
        "Status - conscious",
        "Frail",
        "Influential",
        "Dynamic",
        "Stringent",
        "Lingering",
    ],
    "Values": [
        "Prudent",
        "Self - centered",
        "Fluent",
        "Idealistic",
        "Jovial",
        "Unconcerned",
        "Careful",
        "Diligent",
        "Facilitating",
        "Particular",
        "Compliant",
        "Conservative",
        "Loquacious",
        "Moody",
        "Spatial",
        "Sensing",
        "Polished",
        "Supportive",
        "Strict",
        "Easily distracted",
        "Farsighted",
        "Acute",
        "Pondering",
        "Painstaking",
    ],
    "Planning": [
        "Resourceful",
        "Supportive",
        "Accepting",
        "Risk-averse",
        "Gullible",
        "Spatial",
        "Resolute",
        "Fashionable",
        "Laid Back",
    ],
    "Problem Solving": [
        "Careful",
        "Preoccupied",
        "Intelligent",
        "Commanding",
        "Cheerful",
        "Lingering",
        "Efficient",
        "Moody",
        "Knowledgeable",
    ],
    "Ingenuity": [
        "Aware",
        "Interactive",
        "Pondering",
        "Nit Picky",
        "Dispirited",
        "Original",
        "Bold",
        "Attractive",
        "Systematic",
    ],
    "Goal orientation": [
        "Precise",
        "Emotional",
        "Innovative",
        "Daring",
        "Sensing",
        "Tranquil",
        "Frugal",
        "Impulsive",
        "Inquisitive",
    ],
    "Self-reflection": [
        "Opportunistic",
        "Endearing",
        "Restful",
        "Exacting",
        "Ashamed",
        "Astute",
        "Fastidious",
        "Dynamic",
        "Sociable",
    ],
    "Endurance & capacity": [
        "Calm",
        "Controlled",
        "Restless",
        "Incisive",
        "Fearless",
        "Conversational",
        "Unconcerned",
        "Compliant",
        "Rattled",
    ],
    "Monotony tolerance": [
        "Clever",
        "Decisive",
        "Loquacious",
        "Nonchalant",
        "Observant",
        "Temperamental",
        "Experimental",
        "Idealistic",
        "Jovial",
    ],
    "Flexibility": [
        "At Ease",
        "Traditional",
        "Cynical",
        "Shrewd",
        "Self-confident",
        "Popular",
        "Steady",
        "Conventional",
        "Sensitive",
    ],
    "Analytical thinking": [
        "Analytical",
        "Ambitious",
        "Communicative",
        "Comfortable",
        "Accurate",
        "Forgetful",
        "Facilitating",
        "Individualistic",
        "Formal",
    ],
    "Learning ability": [
        "Peaceful",
        "Painstaking",
        "Anxious",
        "Agile",
        "Dogmatic",
        "Perfectionist",
        "Courageous",
        "Expressive",
        "Unhurried",
    ],
    "Conformity": [
        "Organized",
        "Easily Excited",
        "Creative",
        "Relentless",
        "Talkative",
        "Even Tempered",
        "Stringent",
        "Fearful",
        "Acute",
    ],
    "Accuracy": [
        "Self-assured",
        "Good Mixer",
        "Relaxed",
        "Flawless",
        "Immature",
        "Farsighted",
        "Persistent",
        "Outgoing",
        "Modest",

    ],
    "Speed": [
        "Respectful",
        "Reluctant",
        "Perceptive",
        "Pessimistic",
        "Playful",
        "Patient",
        "Vigilant",
        "Suggestible",
        "Deductive",
    ],
    "Multitask skills": [
        "Influential",
        "Spontaneous",
        "Consistent",
        "Watchful",
        "Confused",
        "Insightful",
        "Purposeful",
        "Rigorous",
        "Placid",
    ],
    "Task switching": [
        "Thorough",
        "Frail",
        "Inventive",
        "Historical",
        "Prudent",
        "Strong Willed",
        "Likable",
        "Status-conscious",
        "Structured",
    ],
    "Typing accuracy": [
        "Sentimental",
        "Savvy",
        "Unwavering",
        "Polished",
        "Unruffled",
        "Finite",
        "Perplexed",
        "Keen",
        "Demanding",
    ],
    "Typing speed": [
        "Easy Going",
        "Strict",
        "Self-centered",
        "Venturesome",
        "Entertaining",
        "Determined",
        "Cautious",
        "Fragile",
        "Predictable",
    ],
    "Working memeory": [
        "Indulgent",
        "Nervous",
        "Conservative",
        "Easily Distracted",
        "Self-reliant",
        "Life of the Party",
        "Single-minded",
        "Conforming",
        "Pedantic",
    ],
}


export default DATA;





// "Appealing",
// "Approachable",
// "Orderly",
// "Chatty",
// "Fluent",
// "Diligent",
// "Particular",
// "Meticulous",
// "Disciplined",
// "Thrifty",
// "Old Fashioned",
// "Crisp",
